import { existsSync } from "node:fs";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { memoryRoot } from "../../../storage/paths.js";

export type RuntimeScriptTarget = "hooks" | "plugin-scripts";

export interface MaterializeRuntimeScriptsOptions {
  /** Package / repo root that contains `dist/hooks/*.mjs`. */
  repoDir?: string;
  /** Vault root (default: memoryRoot()). */
  vaultRoot?: string;
  /**
   * Which launcher directories to write.
   * - `hooks` → `<vault>/hooks/` (Hermes, Pi, OpenClaw, OpenCode)
   * - `plugin-scripts` → `<vault>/claude-code-plugin/scripts/` (Claude Code, Codex, Desktop, VS Code, Antigravity MCP)
   */
  targets?: RuntimeScriptTarget[];
  /** Header comment in generated launchers. */
  generatedBy?: string;
}

export interface MaterializeRuntimeScriptsResult {
  sourceDir: string;
  written: string[];
  hooksDir: string | null;
  pluginScriptsDir: string | null;
}

/**
 * Materialize thin ESM launchers that re-export the built hook entrypoints
 * under the vault so installers can point client configs at stable paths.
 *
 * Launchers use absolute `file://` imports of `dist/hooks/*.mjs` so a single
 * npm/global install of memory-fort can serve many clients without copying
 * large bundles into the vault.
 */
export async function materializeRuntimeScripts(
  opts: MaterializeRuntimeScriptsOptions = {},
): Promise<MaterializeRuntimeScriptsResult> {
  const vault = opts.vaultRoot ?? memoryRoot();
  const repoDir = opts.repoDir ?? process.env["MEMORY_REPO_DIR"] ?? resolvePackageRoot();
  const sourceDir = join(repoDir, "dist", "hooks");
  const targets = opts.targets ?? ["hooks", "plugin-scripts"];
  const generatedBy = opts.generatedBy ?? "memory install";

  if (!existsSync(sourceDir)) {
    throw new Error(
      `repo hooks dir not built: ${sourceDir} — run 'npm run build' first (or set MEMORY_REPO_DIR to a built checkout)`,
    );
  }

  const entries = await readdir(sourceDir, { withFileTypes: true });
  const hookFiles = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".mjs"))
    .map((entry) => entry.name)
    .sort();

  if (hookFiles.length === 0) {
    throw new Error(`no hook launchers found under ${sourceDir}`);
  }

  const written: string[] = [];
  let hooksOut: string | null = null;
  let pluginOut: string | null = null;

  if (targets.includes("hooks")) {
    hooksOut = join(vault, "hooks");
    written.push(...(await writeLauncherDir(sourceDir, hooksOut, hookFiles, generatedBy)));
  }

  if (targets.includes("plugin-scripts")) {
    pluginOut = join(vault, "claude-code-plugin", "scripts");
    written.push(...(await writeLauncherDir(sourceDir, pluginOut, hookFiles, generatedBy)));
  }

  return {
    sourceDir,
    written,
    hooksDir: hooksOut,
    pluginScriptsDir: pluginOut,
  };
}

/** Ensure vault-local `hooks/` launchers exist (Hermes / Pi / OpenClaw / OpenCode). */
export async function ensureVaultHookScripts(
  opts: Omit<MaterializeRuntimeScriptsOptions, "targets"> = {},
): Promise<MaterializeRuntimeScriptsResult> {
  return materializeRuntimeScripts({ ...opts, targets: ["hooks"] });
}

/** Ensure Claude-plugin-style `claude-code-plugin/scripts/` launchers exist. */
export async function ensurePluginScriptLaunchers(
  opts: Omit<MaterializeRuntimeScriptsOptions, "targets"> = {},
): Promise<MaterializeRuntimeScriptsResult> {
  return materializeRuntimeScripts({ ...opts, targets: ["plugin-scripts"] });
}

export function resolvePackageRoot(startDir?: string): string {
  // fileURLToPath decodes %20 etc.; bare URL.pathname breaks installs under
  // paths with spaces (e.g. Windows "Jane Doe" profiles).
  let dir = startDir ?? dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 10; i++) {
    if (existsSync(join(dir, "package.json"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error("Could not locate package root from script location");
}

async function writeLauncherDir(
  sourceDir: string,
  targetDir: string,
  hookFiles: string[],
  generatedBy: string,
): Promise<string[]> {
  await rm(targetDir, { recursive: true, force: true });
  await mkdir(targetDir, { recursive: true });
  const written: string[] = [];
  for (const name of hookFiles) {
    const targetHref = pathToFileURL(join(sourceDir, name)).href;
    const targetPath = join(targetDir, name);
    await writeFile(
      targetPath,
      [
        `// Generated by ${generatedBy}.`,
        `export const memoryHookTarget = ${JSON.stringify(targetHref)};`,
        "await import(memoryHookTarget);",
        "",
      ].join("\n"),
      "utf-8",
    );
    written.push(targetPath);
  }
  return written;
}
