import { existsSync } from "node:fs";
import { mkdir, readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { atomicAppend, atomicWrite } from "../../../storage/atomic-write.js";
import { logPath, memoryRoot } from "../../../storage/paths.js";

export interface InstallOpenCodeOptions {
  opencodeDir?: string;
  now?: Date;
}

export interface InstallOpenCodeResult {
  configPath: string;
  pluginPath: string;
  configCreated: boolean;
  memoryEntryAction: "created" | "updated" | "unchanged";
  preservedServerCount: number;
  log: string[];
}

export function opencodeConfigDir(override?: string): string {
  if (override && override.trim().length > 0) return override;
  const envOverride = process.env["MEMORY_OPENCODE_DIR"];
  if (envOverride && envOverride.trim().length > 0) return envOverride;
  const officialConfigDir = process.env["OPENCODE_CONFIG_DIR"];
  if (officialConfigDir && officialConfigDir.trim().length > 0) return officialConfigDir;
  return join(homedir(), ".config", "opencode");
}

export function opencodeConfigPath(opencodeDir = opencodeConfigDir()): string {
  return join(opencodeDir, "opencode.json");
}

export function opencodePluginPath(opencodeDir = opencodeConfigDir()): string {
  return join(opencodeDir, "plugins", "memory-fort.js");
}

export async function runInstallOpenCode(
  opts: InstallOpenCodeOptions = {},
): Promise<InstallOpenCodeResult> {
  const configDir = opencodeConfigDir(opts.opencodeDir);
  const configPath = opencodeConfigPath(configDir);
  const pluginPath = opencodePluginPath(configDir);
  const log: string[] = [];
  let existingConfig: Record<string, unknown> = {};
  let configCreated = false;

  if (existsSync(configPath)) {
    const raw = await readFile(configPath, "utf-8");
    try {
      existingConfig = parseJsonObject(raw);
    } catch (err) {
      throw new Error(
        `memory install opencode: failed to parse existing config at ${configPath}: ${(err as Error).message}`,
      );
    }
  } else {
    configCreated = true;
    await mkdir(dirname(configPath), { recursive: true });
  }

  const existingMcp = existingConfig["mcp"];
  const mcp: Record<string, unknown> = isRecord(existingMcp)
    ? { ...existingMcp }
    : {};

  const memoryEntry = {
    type: "local",
    command: ["node", `${memoryRoot().replace(/\\/g, "/")}/hooks/mcp-server.mjs`],
    enabled: true,
  };

  const existingMemory = mcp["memory"];
  let memoryEntryAction: "created" | "updated" | "unchanged";
  if (existingMemory === undefined) {
    memoryEntryAction = "created";
  } else if (JSON.stringify(existingMemory) === JSON.stringify(memoryEntry)) {
    memoryEntryAction = "unchanged";
  } else {
    memoryEntryAction = "updated";
  }

  mcp["memory"] = memoryEntry;
  const preservedServerCount = Object.keys(mcp).length - 1;
  const finalConfig = { ...existingConfig, mcp };

  await atomicWrite(configPath, `${JSON.stringify(finalConfig, null, 2)}\n`);
  await atomicWrite(pluginPath, renderOpenCodePlugin());

  log.push(
    configCreated
      ? `created ${configPath} with memory MCP entry`
      : `${memoryEntryAction} memory MCP entry in ${configPath}`,
  );
  log.push(`installed OpenCode Memory Fort plugin at ${pluginPath}`);

  const now = opts.now ?? new Date();
  await atomicAppend(
    logPath(),
    `## [${now.toISOString()}] install | opencode: MCP entry in ${configPath}; plugin in ${pluginPath}\n`,
  );

  return {
    configPath,
    pluginPath,
    configCreated,
    memoryEntryAction,
    preservedServerCount,
    log,
  };
}

function parseJsonObject(raw: string): Record<string, unknown> {
  const parsed = raw.trim().length === 0 ? {} : JSON.parse(raw);
  if (!isRecord(parsed)) {
    throw new Error("expected top-level JSON object");
  }
  return parsed;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function renderOpenCodePlugin(): string {
  const eventHook = `${memoryRoot().replace(/\\/g, "/")}/hooks/opencode-event.mjs`;
  return [
    "// Generated by memory-fort. Re-run `memory-fort install opencode` to update.",
    "export const MemoryFortOpenCode = async ({ $ }) => {",
    `  const script = ${JSON.stringify(eventHook)};`,
    "  async function record(event) {",
    "    await $`node ${script}`.stdin(JSON.stringify(event));",
    "  }",
    "  return {",
    "    event: async ({ event }) => {",
    '      if (event?.type === "session.created" || event?.type === "session.idle" || event?.type === "tool.execute.after") {',
    "        await record(event);",
    "      }",
    "    },",
    "  };",
    "};",
    "",
    "export default MemoryFortOpenCode;",
    "",
  ].join("\n");
}
