import { existsSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { basename, join, relative } from "node:path";
import { atomicWrite } from "../storage/atomic-write.js";
import { parseFrontmatter } from "../storage/frontmatter.js";
import type { PageType } from "../storage/paths.js";

export interface RebuildIndexResult {
  path: string;
  changed: boolean;
  content: string;
  entries: number;
}

interface IndexPage {
  path: string;
  title: string;
  summary: string;
  type: PageType;
}

const PAGE_SECTIONS: Array<{ type: PageType; heading: string }> = [
  { type: "preferences", heading: "Preferences" },
  { type: "projects", heading: "Projects" },
  { type: "people", heading: "People" },
  { type: "decisions", heading: "Decisions" },
  { type: "lessons", heading: "Lessons" },
  { type: "references", heading: "References" },
  { type: "tools", heading: "Tools" },
  { type: "threads", heading: "Threads" },
  { type: "procedures", heading: "Procedures" },
  { type: "prospective", heading: "Prospective" },
];

const PAGE_TYPE_SET = new Set<PageType>(PAGE_SECTIONS.map((section) => section.type));

export async function rebuildIndex(vaultRoot: string, opts: { plan?: boolean } = {}): Promise<RebuildIndexResult> {
  const indexPath = join(vaultRoot, "index.md");
  const pages = await listIndexPages(vaultRoot);
  const content = renderIndex(pages);
  const current = existsSync(indexPath) ? await readFile(indexPath, "utf-8") : "";
  const changed = current !== content;
  if (changed && !opts.plan) {
    await atomicWrite(indexPath, content);
  }
  return {
    path: "index.md",
    changed,
    content,
    entries: pages.length,
  };
}

async function listIndexPages(vaultRoot: string): Promise<IndexPage[]> {
  const wikiRoot = join(vaultRoot, "wiki");
  if (!existsSync(wikiRoot)) return [];
  const files: string[] = [];

  async function walk(dir: string): Promise<void> {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      const rel = relative(wikiRoot, fullPath).replace(/\\/g, "/");
      if (entry.isDirectory()) {
        if (shouldExcludeWikiRelPath(rel)) continue;
        await walk(fullPath);
      } else if (entry.isFile() && entry.name.endsWith(".md") && !shouldExcludeWikiRelPath(rel)) {
        files.push(fullPath);
      }
    }
  }

  await walk(wikiRoot);

  const pages: IndexPage[] = [];
  const seen = new Set<string>();
  for (const file of files.sort((a, b) => a.localeCompare(b))) {
    const relPath = `wiki/${relative(wikiRoot, file).replace(/\\/g, "/")}`;
    if (seen.has(relPath)) continue;
    seen.add(relPath);
    const parsed = parseFrontmatter(await readFile(file, "utf-8"));
    const type = readPageType(parsed.frontmatter.type, relPath);
    if (!type) continue;
    pages.push({
      path: relPath,
      type,
      title: readTitle(parsed.frontmatter.title, relPath),
      summary: readSummary(parsed.body, parsed.frontmatter.title, relPath),
    });
  }
  return pages;
}

function shouldExcludeWikiRelPath(relPath: string): boolean {
  return relPath
    .replace(/\\/g, "/")
    .split("/")
    // Dot-directories (.audit, .history, …) are operational, not entity pages.
    .some((part) => part.startsWith(".") || part === "archive" || part.endsWith("-proposed"));
}

function readPageType(value: unknown, relPath: string): PageType | null {
  if (typeof value === "string" && PAGE_TYPE_SET.has(value as PageType)) {
    return value as PageType;
  }
  const category = relPath.split("/")[1];
  return category && PAGE_TYPE_SET.has(category as PageType) ? category as PageType : null;
}

function readTitle(value: unknown, relPath: string): string {
  if (typeof value === "string" && value.trim().length > 0) return value.trim();
  return basename(relPath, ".md");
}

function readSummary(body: string, title: unknown, relPath: string): string {
  const line = body
    .split(/\r?\n/)
    .map((item) => item.trim())
    .find((item) => item.length > 0 && !item.startsWith("#"));
  return cleanSummary(line ?? readTitle(title, relPath));
}

function cleanSummary(value: string): string {
  const cleaned = value
    .replace(/^[-*]\s+/, "")
    .replace(/\s+/g, " ")
    .trim();
  return cleaned.length > 240 ? `${cleaned.slice(0, 237)}...` : cleaned;
}

function renderIndex(pages: IndexPage[]): string {
  const lines = [
    "# Index",
    "",
    "*This file is auto-generated by `memory reindex` and `memory compile --execute`. Do not edit manually.*",
  ];

  for (const section of PAGE_SECTIONS) {
    const sectionPages = pages
      .filter((page) => page.type === section.type)
      .sort((a, b) => a.title.localeCompare(b.title) || a.path.localeCompare(b.path));
    if (sectionPages.length === 0) continue;
    lines.push("", `## ${section.heading}`, "");
    for (const page of sectionPages) {
      lines.push(`- [${page.title}](${page.path}) - ${page.summary}`);
    }
  }

  if (pages.length === 0) {
    lines.push("", "No curated pages yet.");
  }

  return `${lines.join("\n")}\n`;
}
