import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { existsSync } from "node:fs";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  ensurePluginScriptLaunchers,
  ensureVaultHookScripts,
  materializeRuntimeScripts,
} from "../../../../src/cli/commands/install/materialize-runtime-scripts.js";
import { seedBuiltHooks } from "./seed-built-hooks.js";

describe("materializeRuntimeScripts", () => {
  let tmp: string;
  let vaultRoot: string;
  let repoDir: string;
  let envBefore: Record<string, string | undefined>;

  beforeEach(async () => {
    tmp = await mkdtemp(join(tmpdir(), "materialize-hooks-"));
    vaultRoot = join(tmp, ".memory");
    repoDir = join(tmp, "repo");
    await seedBuiltHooks(repoDir);
    envBefore = {
      MEMORY_ROOT: process.env["MEMORY_ROOT"],
      MEMORY_REPO_DIR: process.env["MEMORY_REPO_DIR"],
    };
    process.env["MEMORY_ROOT"] = vaultRoot;
  });

  afterEach(async () => {
    for (const [key, value] of Object.entries(envBefore)) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
    await rm(tmp, { recursive: true, force: true });
  });

  it("writes vault hooks launchers that re-export dist/hooks entrypoints", async () => {
    const result = await ensureVaultHookScripts({ repoDir, vaultRoot });

    expect(result.hooksDir).toBe(join(vaultRoot, "hooks"));
    expect(existsSync(join(vaultRoot, "hooks", "mcp-server.mjs"))).toBe(true);
    expect(existsSync(join(vaultRoot, "hooks", "session-start.mjs"))).toBe(true);
    expect(existsSync(join(vaultRoot, "hooks", "opencode-event.mjs"))).toBe(true);

    const launcher = await readFile(join(vaultRoot, "hooks", "mcp-server.mjs"), "utf-8");
    expect(launcher).toContain("Generated by");
    expect(launcher).toContain("memoryHookTarget");
    expect(launcher).toContain("await import(memoryHookTarget)");
    expect(launcher).toMatch(/file:.*mcp-server\.mjs/);
  });

  it("writes claude-code-plugin/scripts launchers for shared MCP clients", async () => {
    const result = await ensurePluginScriptLaunchers({ repoDir, vaultRoot });

    expect(result.pluginScriptsDir).toBe(
      join(vaultRoot, "claude-code-plugin", "scripts"),
    );
    expect(existsSync(join(vaultRoot, "claude-code-plugin", "scripts", "mcp-server.mjs"))).toBe(
      true,
    );
  });

  it("can materialize both targets in one call", async () => {
    const result = await materializeRuntimeScripts({
      repoDir,
      vaultRoot,
      targets: ["hooks", "plugin-scripts"],
    });

    expect(result.written.length).toBeGreaterThanOrEqual(14);
    expect(existsSync(join(vaultRoot, "hooks", "mcp-server.mjs"))).toBe(true);
    expect(
      existsSync(join(vaultRoot, "claude-code-plugin", "scripts", "mcp-server.mjs")),
    ).toBe(true);
  });

  it("fails with a clear error when dist/hooks is missing", async () => {
    const emptyRepo = join(tmp, "empty-repo");
    await seedBuiltHooks(emptyRepo, []);
    await rm(join(emptyRepo, "dist"), { recursive: true, force: true });

    await expect(
      ensureVaultHookScripts({ repoDir: emptyRepo, vaultRoot }),
    ).rejects.toThrow(/repo hooks dir not built/);
  });
});
