import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, readFile, readdir, rename } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  memoryRoot,
  schemaPath,
  indexPath,
  logPath,
  errorsLogPath,
  configPath,
} from "../../storage/paths.js";
import { atomicWrite, atomicAppend } from "../../storage/atomic-write.js";
import { detectTemplateVars, renderTemplate } from "../template-render.js";

declare const __MEMORY_BUILD_COMMIT__: string | undefined;

export interface InitOptions {
  reset?: boolean;
  /** Absolute path to the source repo containing templates/. */
  sourceRepoDir?: string;
  /** For tests: override the current date. */
  now?: Date;
}

export interface InitResult {
  root: string;
  created: string[];
  preserved: string[];
  archivedTo?: string;
}

const SUBDIRS = [
  "raw",
  "wiki/projects",
  "wiki/people",
  "wiki/decisions",
  "wiki/lessons",
  "wiki/procedures",
  "wiki/procedures-proposed",
  "wiki/threads",
  "wiki/threads-proposed",
  "wiki/references",
  "wiki/tools",
  "crystals",
  "embeddings",
  "scripts",
  ".archive",
  "prompts",
];

const GITIGNORE_CONTENT = `# Memory runtime artifacts not stored in git
errors.log
.archive/
embeddings/
wiki/.audit/llm-debug-*.md
claude-code-plugin/
`;

const GITATTRIBUTES_CONTENT = `*.md text eol=lf
*.yaml text eol=lf
*.json text eol=lf
`;

const DEFAULT_CONFIG = `# memory-system runtime configuration
# Auto-generated by \`memory init\`. Safe to edit; settings take effect on next CLI invocation.

retention:
  raw_window_days: 90
  raw_compile_before_delete: true
  embeddings_prune_with_raw: true
  wiki_status_stale_days: 180
  crystals_never_auto_delete: true
  archive_before_delete: true

embedder:
  provider: voyage
  model: voyage-4-large

# llm:
#   provider: openrouter   # openrouter | ollama
#   model: openai/gpt-4o-mini
#   max_tokens: 4096
#   temperature: 0.2

embedding:
  # Legacy fallback. New writes should use embedder above.
  provider: voyage
  model: voyage-4-large
  dim: 2048

privacy:
  allowlist: []   # regex patterns that bypass the redaction filter
`;

export async function runInit(opts: InitOptions = {}): Promise<InitResult> {
  const root = memoryRoot();
  const result: InitResult = { root, created: [], preserved: [] };

  if (opts.reset && existsSync(root)) {
    result.archivedTo = await archiveExistingRoot(root, opts.now ?? new Date());
  }

  if (!existsSync(root)) {
    await mkdir(root, { recursive: true });
    result.created.push(root);
  } else {
    result.preserved.push(root);
  }

  for (const sub of SUBDIRS) {
    const path = join(root, sub);
    if (!existsSync(path)) {
      await mkdir(path, { recursive: true });
      result.created.push(path);
    } else {
      result.preserved.push(path);
    }
  }

  if (!existsSync(schemaPath())) {
    const template = await readFile(templatePath(opts.sourceRepoDir), "utf-8");
    const vars = detectTemplateVars({
      sourceRepoDir: opts.sourceRepoDir,
      now: opts.now,
    });
    vars.install_commit = buildInstallCommit(vars.install_commit);
    await atomicWrite(schemaPath(), renderTemplate(template, vars));
    result.created.push(schemaPath());
  } else {
    result.preserved.push(schemaPath());
  }

  // prompts/*.md are copied verbatim; consumers substitute variables at runtime.
  const promptsSourceDir = promptsTemplateDir(opts.sourceRepoDir);
  const promptsDestDir = join(root, "prompts");
  for (const name of ["compile.md", "lint.md", "hyde.md"] as const) {
    const srcPath = join(promptsSourceDir, name);
    const destPath = join(promptsDestDir, name);
    if (!existsSync(destPath) && existsSync(srcPath)) {
      const content = await readFile(srcPath, "utf-8");
      await atomicWrite(destPath, content);
      result.created.push(destPath);
    } else if (existsSync(destPath)) {
      result.preserved.push(destPath);
    }
  }

  if (!existsSync(indexPath())) {
    await atomicWrite(
      indexPath(),
      "# Index\n\n" +
        "*This file is auto-generated by `memory compile`. Do not edit manually.*\n\n" +
        "No curated pages yet.\n",
    );
    result.created.push(indexPath());
  } else {
    result.preserved.push(indexPath());
  }

  const initLine =
    `## [${(opts.now ?? new Date()).toISOString()}] init | ` +
    `memory-system initialized at ${root}\n`;
  if (!existsSync(logPath())) {
    await atomicWrite(logPath(), `# Log\n\n${initLine}`);
    result.created.push(logPath());
  } else {
    await atomicAppend(logPath(), initLine);
    result.preserved.push(logPath());
  }

  if (!existsSync(configPath())) {
    await atomicWrite(configPath(), DEFAULT_CONFIG);
    result.created.push(configPath());
  } else {
    result.preserved.push(configPath());
  }

  if (!existsSync(errorsLogPath())) {
    await atomicWrite(errorsLogPath(), "");
    result.created.push(errorsLogPath());
  } else {
    result.preserved.push(errorsLogPath());
  }

  const gitignore = join(root, ".gitignore");
  if (!existsSync(gitignore)) {
    await atomicWrite(gitignore, GITIGNORE_CONTENT);
    result.created.push(gitignore);
  } else {
    result.preserved.push(gitignore);
  }

  const gitattributes = join(root, ".gitattributes");
  if (!existsSync(gitattributes)) {
    await atomicWrite(gitattributes, GITATTRIBUTES_CONTENT);
    result.created.push(gitattributes);
  } else {
    result.preserved.push(gitattributes);
  }

  if (!existsSync(join(root, ".git"))) {
    try {
      execFileSync("git", ["init", "-q", "-b", "main"], {
        cwd: root,
        stdio: ["ignore", "ignore", "ignore"],
      });
      const vars = detectTemplateVars({ now: opts.now });
      execFileSync("git", ["config", "user.name", vars.user_name], {
        cwd: root,
        stdio: ["ignore", "ignore", "ignore"],
      });
      execFileSync("git", ["config", "user.email", vars.user_email], {
        cwd: root,
        stdio: ["ignore", "ignore", "ignore"],
      });
      execFileSync(
        "git",
        [
          "add",
          "schema.md",
          "index.md",
          "log.md",
          "config.yaml",
          ".gitignore",
          ".gitattributes",
        ],
        { cwd: root, stdio: ["ignore", "ignore", "ignore"] },
      );
      execFileSync("git", ["commit", "-q", "-m", "chore: memory init"], {
        cwd: root,
        stdio: ["ignore", "ignore", "ignore"],
      });
      result.created.push(join(root, ".git"));
    } catch {
      // git not available; that's ok — files exist, user can git-init manually
    }
  } else {
    result.preserved.push(join(root, ".git"));
  }

  return result;
}

function buildInstallCommit(detectedCommit: string): string {
  if (typeof __MEMORY_BUILD_COMMIT__ !== "undefined") {
    return __MEMORY_BUILD_COMMIT__;
  }
  return detectedCommit;
}

async function archiveExistingRoot(root: string, now: Date): Promise<string> {
  const ts = now.toISOString().replace(/[:.]/g, "-");
  const archive = join(root, ".archive", `pre-reset-${ts}`);
  await mkdir(archive, { recursive: true });

  const entries = await readdir(root, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === ".archive") continue;
    await rename(join(root, entry.name), join(archive, entry.name));
  }

  return archive;
}

function templatePath(sourceRepoDir?: string): string {
  if (sourceRepoDir) return join(sourceRepoDir, "templates", "schema.md");
  return resolve(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "templates",
    "schema.md",
  );
}

function promptsTemplateDir(sourceRepoDir?: string): string {
  if (sourceRepoDir) return join(sourceRepoDir, "templates", "prompts");
  return resolve(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "templates",
    "prompts",
  );
}
